//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added as option.
        /// </summary>
        public static string AddAnswer {
            get {
                return ResourceManager.GetString("AddAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the page Go to the Item.
        /// </summary>
        public static string AfterCreatePage {
            get {
                return ResourceManager.GetString("AfterCreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable.
        /// </summary>
        public static string AllowEdit {
            get {
                return ResourceManager.GetString("AllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text answer.
        /// </summary>
        public static string AnswerContent {
            get {
                return ResourceManager.GetString("AnswerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one option must be selected as a question..
        /// </summary>
        public static string AnswerOptionError {
            get {
                return ResourceManager.GetString("AnswerOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Book Creator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new item.
        /// </summary>
        public static string CreateItem {
            get {
                return ResourceManager.GetString("CreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to delete?.
        /// </summary>
        public static string DeletePrompt {
            get {
                return ResourceManager.GetString("DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Success.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel upload.
        /// </summary>
        public static string dictCancelUpload {
            get {
                return ResourceManager.GetString("dictCancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this upload?.
        /// </summary>
        public static string dictCancelUploadConfirmation {
            get {
                return ResourceManager.GetString("dictCancelUploadConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here to upload (width: 400 - Height: 300).
        /// </summary>
        public static string dictDefaultMessageImage {
            get {
                return ResourceManager.GetString("dictDefaultMessageImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here to upload (mp3 / wav).
        /// </summary>
        public static string dictDefaultMessageSound {
            get {
                return ResourceManager.GetString("dictDefaultMessageSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser does not support drag&apos;n&apos;drop file uploads..
        /// </summary>
        public static string dictFallbackMessage {
            get {
                return ResourceManager.GetString("dictFallbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the fallback form below to upload your files like in the olden days..
        /// </summary>
        public static string dictFallbackText {
            get {
                return ResourceManager.GetString("dictFallbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too big ({{filesize}}MiB). Max filesize: {{maxFilesize}}MiB..
        /// </summary>
        public static string dictFileTooBig {
            get {
                return ResourceManager.GetString("dictFileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t upload files of this type..
        /// </summary>
        public static string dictInvalidFileType {
            get {
                return ResourceManager.GetString("dictInvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not upload any more files..
        /// </summary>
        public static string dictMaxFilesExceeded {
            get {
                return ResourceManager.GetString("dictMaxFilesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file.
        /// </summary>
        public static string dictRemoveFile {
            get {
                return ResourceManager.GetString("dictRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server responded with {{statusCode}} code..
        /// </summary>
        public static string dictResponseError {
            get {
                return ResourceManager.GetString("dictResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information..
        /// </summary>
        public static string EnterEmptyInputs {
            get {
                return ResourceManager.GetString("EnterEmptyInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  like : http://youtube.com .
        /// </summary>
        public static string EnterUrl {
            get {
                return ResourceManager.GetString("EnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color package can not be empty.
        /// </summary>
        public static string ErrorColor {
            get {
                return ResourceManager.GetString("ErrorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter content.
        /// </summary>
        public static string ErrorContent {
            get {
                return ResourceManager.GetString("ErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can not be empty.
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items must be entered as.
        /// </summary>
        public static string ErrorItemTitle {
            get {
                return ResourceManager.GetString("ErrorItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter language.
        /// </summary>
        public static string ErrorLanguage {
            get {
                return ResourceManager.GetString("ErrorLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson number can not be empty.
        /// </summary>
        public static string ErrorlessonId {
            get {
                return ResourceManager.GetString("ErrorlessonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Course.
        /// </summary>
        public static string ErrorLessonTitle {
            get {
                return ResourceManager.GetString("ErrorLessonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the icon.
        /// </summary>
        public static string ErrorLogo {
            get {
                return ResourceManager.GetString("ErrorLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Media.
        /// </summary>
        public static string ErrorMedia {
            get {
                return ResourceManager.GetString("ErrorMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training methods should be chosen.
        /// </summary>
        public static string ErrorMethodId {
            get {
                return ResourceManager.GetString("ErrorMethodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the desired method.
        /// </summary>
        public static string ErrorMethodName {
            get {
                return ResourceManager.GetString("ErrorMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package name must be entered.
        /// </summary>
        public static string ErrorPackName {
            get {
                return ResourceManager.GetString("ErrorPackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Page Type.
        /// </summary>
        public static string ErrorPageTypeId {
            get {
                return ResourceManager.GetString("ErrorPageTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of room to be imported.
        /// </summary>
        public static string ErrorRoomCount {
            get {
                return ResourceManager.GetString("ErrorRoomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving image file.
        /// </summary>
        public static string ErrorSaveImage {
            get {
                return ResourceManager.GetString("ErrorSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the desired sound..
        /// </summary>
        public static string ErrorSound {
            get {
                return ResourceManager.GetString("ErrorSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Store Type.
        /// </summary>
        public static string ErrorStoreType {
            get {
                return ResourceManager.GetString("ErrorStoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic must be selected.
        /// </summary>
        public static string ErrorSubjectId {
            get {
                return ResourceManager.GetString("ErrorSubjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Subject.
        /// </summary>
        public static string ErrorSubjectName {
            get {
                return ResourceManager.GetString("ErrorSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the video track..
        /// </summary>
        public static string ErrorVideo {
            get {
                return ResourceManager.GetString("ErrorVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashCard.
        /// </summary>
        public static string FlashCard {
            get {
                return ResourceManager.GetString("FlashCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FooDate {
            get {
                return ResourceManager.GetString("FooDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string FooEnable {
            get {
                return ResourceManager.GetString("FooEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titile.
        /// </summary>
        public static string FooTitle {
            get {
                return ResourceManager.GetString("FooTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size Error image size to a width of 400 and a height of 300 is.
        /// </summary>
        public static string ImagesSizeError {
            get {
                return ResourceManager.GetString("ImagesSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer options.
        /// </summary>
        public static string IsAnswer {
            get {
                return ResourceManager.GetString("IsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Fill.
        /// </summary>
        public static string ItemFill {
            get {
                return ResourceManager.GetString("ItemFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Html Format.
        /// </summary>
        public static string ItemHTML {
            get {
                return ResourceManager.GetString("ItemHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Multiple choice.
        /// </summary>
        public static string ItemMultipleChoice {
            get {
                return ResourceManager.GetString("ItemMultipleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number.
        /// </summary>
        public static string ItemNumber {
            get {
                return ResourceManager.GetString("ItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question One choice.
        /// </summary>
        public static string ItemOnechoice {
            get {
                return ResourceManager.GetString("ItemOnechoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Ordering.
        /// </summary>
        public static string ItemOrdering {
            get {
                return ResourceManager.GetString("ItemOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Picture.
        /// </summary>
        public static string ItemPicture {
            get {
                return ResourceManager.GetString("ItemPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Placement.
        /// </summary>
        public static string ItemPlacement {
            get {
                return ResourceManager.GetString("ItemPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Sound.
        /// </summary>
        public static string ItemSound {
            get {
                return ResourceManager.GetString("ItemSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Speech.
        /// </summary>
        public static string ItemTTS {
            get {
                return ResourceManager.GetString("ItemTTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string ItemTypeId {
            get {
                return ResourceManager.GetString("ItemTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Video.
        /// </summary>
        public static string ItemVideo {
            get {
                return ResourceManager.GetString("ItemVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson.
        /// </summary>
        public static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new lesson.
        /// </summary>
        public static string LessonCreate {
            get {
                return ResourceManager.GetString("LessonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessonNumber.
        /// </summary>
        public static string LessonNumber {
            get {
                return ResourceManager.GetString("LessonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Methods.
        /// </summary>
        public static string MethodId {
            get {
                return ResourceManager.GetString("MethodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Methods.
        /// </summary>
        public static string MethodSelect {
            get {
                return ResourceManager.GetString("MethodSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one option must be selected as the answer.
        /// </summary>
        public static string MultipleCountError {
            get {
                return ResourceManager.GetString("MultipleCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Support text to Speech - Please use Chrome https://www.google.com/chrome/browser/desktop/index.html .
        /// </summary>
        public static string NotSupportTTS {
            get {
                return ResourceManager.GetString("NotSupportTTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One option must be selected as the answer.
        /// </summary>
        public static string OneCountError {
            get {
                return ResourceManager.GetString("OneCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Options to be more than one.
        /// </summary>
        public static string OptionsCountError {
            get {
                return ResourceManager.GetString("OptionsCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options can not be empty.
        /// </summary>
        public static string OptionsNotEmpty {
            get {
                return ResourceManager.GetString("OptionsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Pack {
            get {
                return ResourceManager.GetString("Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Package.
        /// </summary>
        public static string PackCreate {
            get {
                return ResourceManager.GetString("PackCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a new multimedia training package (text, image, audio, four options, flash cards) can use this field. For example, a basic math education, cooking lessons, ....
        /// </summary>
        public static string PackDescription {
            get {
                return ResourceManager.GetString("PackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Packages.
        /// </summary>
        public static string PackList {
            get {
                return ResourceManager.GetString("PackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Name.
        /// </summary>
        public static string PackName {
            get {
                return ResourceManager.GetString("PackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new page.
        /// </summary>
        public static string PageCreate {
            get {
                return ResourceManager.GetString("PageCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Type.
        /// </summary>
        public static string PageType {
            get {
                return ResourceManager.GetString("PageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string ReDir {
            get {
                return ResourceManager.GetString("ReDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type.
        /// </summary>
        public static string RESOURCE_TYPE_ID {
            get {
                return ResourceManager.GetString("RESOURCE_TYPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Number.
        /// </summary>
        public static string ResourceID {
            get {
                return ResourceManager.GetString("ResourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room count.
        /// </summary>
        public static string RoomCount {
            get {
                return ResourceManager.GetString("RoomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Image.
        /// </summary>
        public static string SearchImage {
            get {
                return ResourceManager.GetString("SearchImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Training Package.
        /// </summary>
        public static string SelectPack {
            get {
                return ResourceManager.GetString("SelectPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files saved.
        /// </summary>
        public static string ShowFiles {
            get {
                return ResourceManager.GetString("ShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Type.
        /// </summary>
        public static string StoreType {
            get {
                return ResourceManager.GetString("StoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SubjectId {
            get {
                return ResourceManager.GetString("SubjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subject.
        /// </summary>
        public static string SubjectSelect {
            get {
                return ResourceManager.GetString("SubjectSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string TextAlign {
            get {
                return ResourceManager.GetString("TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Speech.
        /// </summary>
        public static string TextToSpeech {
            get {
                return ResourceManager.GetString("TextToSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string UnSuccess {
            get {
                return ResourceManager.GetString("UnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        public static string UploadImages {
            get {
                return ResourceManager.GetString("UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload multiple images for mass and then use it in lessons..
        /// </summary>
        public static string UploadImagesDescription {
            get {
                return ResourceManager.GetString("UploadImagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Sound.
        /// </summary>
        public static string UploadSound {
            get {
                return ResourceManager.GetString("UploadSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload multiple Sound for mass and then use it in lessons..
        /// </summary>
        public static string UploadSoundDescription {
            get {
                return ResourceManager.GetString("UploadSoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
    }
}
