//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable.
        /// </summary>
        public static string AllowEdit {
            get {
                return ResourceManager.GetString("AllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Book Creator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel upload.
        /// </summary>
        public static string dictCancelUpload {
            get {
                return ResourceManager.GetString("dictCancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this upload?.
        /// </summary>
        public static string dictCancelUploadConfirmation {
            get {
                return ResourceManager.GetString("dictCancelUploadConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here to upload.
        /// </summary>
        public static string dictDefaultMessage {
            get {
                return ResourceManager.GetString("dictDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser does not support drag&apos;n&apos;drop file uploads..
        /// </summary>
        public static string dictFallbackMessage {
            get {
                return ResourceManager.GetString("dictFallbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the fallback form below to upload your files like in the olden days..
        /// </summary>
        public static string dictFallbackText {
            get {
                return ResourceManager.GetString("dictFallbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too big ({{filesize}}MiB). Max filesize: {{maxFilesize}}MiB..
        /// </summary>
        public static string dictFileTooBig {
            get {
                return ResourceManager.GetString("dictFileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t upload files of this type..
        /// </summary>
        public static string dictInvalidFileType {
            get {
                return ResourceManager.GetString("dictInvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not upload any more files..
        /// </summary>
        public static string dictMaxFilesExceeded {
            get {
                return ResourceManager.GetString("dictMaxFilesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file.
        /// </summary>
        public static string dictRemoveFile {
            get {
                return ResourceManager.GetString("dictRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server responded with {{statusCode}} code..
        /// </summary>
        public static string dictResponseError {
            get {
                return ResourceManager.GetString("dictResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color package can not be empty.
        /// </summary>
        public static string ErrorColor {
            get {
                return ResourceManager.GetString("ErrorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can not be empty.
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter language.
        /// </summary>
        public static string ErrorLanguage {
            get {
                return ResourceManager.GetString("ErrorLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the icon.
        /// </summary>
        public static string ErrorLogo {
            get {
                return ResourceManager.GetString("ErrorLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training methods should be chosen.
        /// </summary>
        public static string ErrorMethodId {
            get {
                return ResourceManager.GetString("ErrorMethodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the desired method.
        /// </summary>
        public static string ErrorMethodName {
            get {
                return ResourceManager.GetString("ErrorMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package name must be entered.
        /// </summary>
        public static string ErrorPackName {
            get {
                return ResourceManager.GetString("ErrorPackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of room to be imported.
        /// </summary>
        public static string ErrorRoomCount {
            get {
                return ResourceManager.GetString("ErrorRoomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic must be selected.
        /// </summary>
        public static string ErrorSubjectId {
            get {
                return ResourceManager.GetString("ErrorSubjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Subject.
        /// </summary>
        public static string ErrorSubjectName {
            get {
                return ResourceManager.GetString("ErrorSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FooDate {
            get {
                return ResourceManager.GetString("FooDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string FooEnable {
            get {
                return ResourceManager.GetString("FooEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titile.
        /// </summary>
        public static string FooTitle {
            get {
                return ResourceManager.GetString("FooTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Methods.
        /// </summary>
        public static string MethodId {
            get {
                return ResourceManager.GetString("MethodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching Methods.
        /// </summary>
        public static string MethodSelect {
            get {
                return ResourceManager.GetString("MethodSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Pack {
            get {
                return ResourceManager.GetString("Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Package.
        /// </summary>
        public static string PackCreate {
            get {
                return ResourceManager.GetString("PackCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a new multimedia training package (text, image, audio, four options, flash cards) can use this field. For example, a basic math education, cooking lessons, ....
        /// </summary>
        public static string PackDescription {
            get {
                return ResourceManager.GetString("PackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackId.
        /// </summary>
        public static string PackId {
            get {
                return ResourceManager.GetString("PackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Packages.
        /// </summary>
        public static string PackList {
            get {
                return ResourceManager.GetString("PackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Name.
        /// </summary>
        public static string PackName {
            get {
                return ResourceManager.GetString("PackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room count.
        /// </summary>
        public static string RoomCount {
            get {
                return ResourceManager.GetString("RoomCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SubjectId {
            get {
                return ResourceManager.GetString("SubjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Subject.
        /// </summary>
        public static string SubjectSelect {
            get {
                return ResourceManager.GetString("SubjectSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        public static string UploadImages {
            get {
                return ResourceManager.GetString("UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload multiple images for mass and then use it in lessons..
        /// </summary>
        public static string UploadImagesDescription {
            get {
                return ResourceManager.GetString("UploadImagesDescription", resourceCulture);
            }
        }
    }
}
